openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: HaakCo Dev Default Api
    url: https://dev.haak.co/api/v1
  - description: HaakCo Prod Default Api
    url: https://haak.co/api/v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HaakCo/HaakCo/1.0.0
info:
  version: "1.0.0"
  title: HaakCo APi
  description: >-
    HaakCo APi
  contact:
    email: contact@haak.co
security:
  - password:
      - read
      - write
paths:
  /me:
    get:
      summary: Current users details
      description: >-
        Current users details.
      responses:
        '200':
          description: OK
      security:
        - OAuth2: [read, write]
      tags:
        - User
  /test/basic_system:
    get:
      summary: Test if server is up and DB and Redis connected
      description: >-
        Test if server is up and DB and Redis connected
      security: []
      responses:
        '200':
          description: OK
      tags:
        - Testing        - User
  /login/register:
    post:
      summary: Register new user
      description: >-
        Test if server is up and DB and Redis connected
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Users name
                  type: string
                email:
                  description: Users email
                  type: string
                password:
                  description: Users password
                  type: string
                password_confirmation:
                  description: Users password confirmation
                  type: string
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    description: Access Token
                    type: string
                  name:
                    description: User Name
                    type: string
                  uuid:
                    description: UUID
                    type: string
      tags:
        - Login
components:
  schemas: {}
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: '/api/v1/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
